
services:
    nginx_bee:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d

        ports:
            - "8070:80"
        depends_on:
            -  app_bee
        container_name: app_bee_nginx


    app_bee:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        environment:
            - TZ=Europe/Moscow
        volumes:
            - ./:/var/www
        container_name: app_bee


    db_bee:
        image: mysql:8.0
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL-DATABASE: LaraBee
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8033:3306"
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: db_bee

    phpmyadmin_bee:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmindb_bee
        environment:
            PMA_HOST: db_bee
            MYSQL_ROOT_PASSWORD: example
        ports:
            - "8030:80"

        depends_on:
            - db_bee
